SELECT 
	ID ,
	DateTime,
	CheckID,
	TovarCode1C  ,
	TovarName  ,
	DocType  ,
	DocNumber  ,
	DocDate  ,
	ProCode ,
	ProName  ,
	ProAsString  ,
	Series  ,
	ShelfLife  ,
	Price  ,
	PurchasePrice  ,
	SellingPrice  ,
	DiscountPrice  ,
	IntQuantity  ,
	FracQuantity ,
	Sum  ,
	Discount  ,
	Akciya  ,
	Coupon  ,
	DiscByDiscCard  ,
	DiscOfSite  ,
	DiscByRecipe  ,
	DiscByBonusCard  ,
	DiscByAkciya  ,
	VSDQuantity ,
	EconomicGroupCode
FROM
	[Central].[dbo].[CheckTables]
WHERE DocDate >= '2023-01-01'