delete from ods.checktables
where DocDate between '{{ AF_INC_BEGIN }}' and '{{ AF_INC_END }}';

INSERT INTO ods.checktables
(
    ID,
	DateTime,
	CheckID,
	TovarCode1C,
	TovarName,
	DocType,
	DocNumber,
	DocDate,
	ProCode,
	ProName,
	ProAsString,
	Series,
	ShelfLife,
	Price,
	PurchasePrice,
	SellingPrice,
	DiscountPrice,
	IntQuantity,
	FracQuantity,
	Sum,
	Discount,
	Akciya,
	Coupon,
	DiscByDiscCard,
	DiscOfSite,
	DiscByRecipe,
	DiscByBonusCard,
	DiscByAkciya,
	VSDQuantity,
	EconomicGroupCode,
    GrossProfitSum ,
    SalesChannel ,
    OrderNumber ,
    DiscountsAsStr ,
    Sk_Akciya ,
    Sk_Zakaz ,
    Sk_Recept ,
    Sk_Bonus ,
    Sk_Okr
    )
SELECT
    ID,
	DateTime,
	CheckID,
	TovarCode1C,
	TovarName,
	DocType,
	DocNumber,
	DocDate,
	ProCode,
	ProName,
	ProAsString,
	Series,
	ShelfLife,
	Price,
	PurchasePrice,
	SellingPrice,
	DiscountPrice,
	IntQuantity,
	FracQuantity,
	Sum,
	Discount,
	Akciya,
	Coupon,
	DiscByDiscCard,
	DiscOfSite,
	DiscByRecipe,
	DiscByBonusCard,
	DiscByAkciya,
	VSDQuantity,
	EconomicGroupCode,
    GrossProfitSum ,
    SalesChannel ,
    OrderNumber ,
    DiscountsAsStr ,
    Sk_Akciya ,
    Sk_Zakaz ,
    Sk_Recept ,
    Sk_Bonus ,
    Sk_Okr
FROM stg_dwh.checktables_inc;