TRUNCATE TABLE core.assortiment_ce_plain;

INSERT INTO core.assortiment_ce_plain (
	IDHeader            ,
	IDTable             ,
	DocDate             ,
	IDdoc               ,
	lineno              ,
	UpdateDate          ,
	IDstore             ,
	IDitem              ,
	CheckID             ,
    Status              ,
    ConsumptionType     ,
    WriteOffFlag        ,
	quantity            ,
	return_quantity     ,
	move_quantity       ,
	revenue             ,
	purchase            ,
    discount            ,
    manufacture         ,
    kind                ,
    Price               ,
    PurchasePrice       ,
    SellingPrice        ,
    DiscountPrice       ,
    IntQuantity         ,
    FracQuantity        ,
    Sum                 ,
    Discount            ,
    Akciya              ,
    Coupon              ,
    DiscByDiscCard      ,
    DiscOfSite          ,
    DiscByRecipe        ,
    DiscByBonusCard     ,
    DiscByAkciya        ,
    VSDQuantity         ,
    EconomicGroupCode
)
SELECT
    Doc.ID                  as IDHeader,
    DocTabl.ID              as IDTable,
	Doc.DocDate             as DocDate,
	TRIM(Doc.DocNumber)     as IDdoc,
	0                       as lineno,
	Doc.DateTime            as UpdateDate,
	TRIM(PharmacyCode)      as IDstore,
	TRIM(TovarCode1C)       as IDitem,
	DocTabl.CheckID         as CheckID,
    Doc.Status              as Status,
    Doc.ConsumptionType     as ConsumptionType,
    Doc.WriteOffFlag        as WriteOffFlag,
	DocTabl.IntQuantity     as quantity,
	DocTabl.FracQuantity    as return_quantity,
	0                       as move_quantity,
	DocTabl.Sum             as revenue ,
	DocTabl.Discount        as discount ,
    DocTabl.PurchasePrice   as purchase ,
	0                       as manufacture,
	NULL                    as kind,
    Price                   as Price,
    PurchasePrice           as PurchasePrice,
    SellingPrice            as SellingPrice,
    DiscountPrice           as DiscountPrice,
    IntQuantity             as IntQuantity,
    FracQuantity            as FracQuantity,
    Sum                     as Sum,
    Discount                as Discount,
    Akciya                  as Akciya,
    Coupon                  as Coupon,
    DiscByDiscCard          as DiscByDiscCard,
    DiscOfSite              as DiscOfSite,
    DiscByRecipe            as DiscByRecipe,
    DiscByBonusCard         as DiscByBonusCard,
    DiscByAkciya            as DiscByAkciya,
    VSDQuantity             as VSDQuantity,
    EconomicGroupCode    	as EconomicGroupCode
FROM 	stg_dwh.checkheaders    AS Doc
LEFT JOIN stg_dwh.checktables   AS DocTabl
	ON TRIM(Doc.DocNumber) = TRIM(DocTabl.DocNumber)
where Doc.DocDate between '2023-10-01' and '2023-10-01'